### ISSUE TITLE
2nd Issue

### ISSUE THREAD

**Issue by orcakitsu** [orcakitsu/issuetest#2]
```yaml
start_date: 2021/11/18
due_date: 2021/11/18
progress: 0.1
parent: 0
```

This is a second issue.
